# Generated by Django 4.2 on 2023-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Moviedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration", models.FloatField()),
                ("ratings", models.FloatField()),
                ("type_movie", models.CharField(default="action", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default="images/none/noimage.jpg", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
